services:
  ollama:
    image: ollama/ollama:rocm
    container_name: localmind_ollama
    devices:
      - /dev/kfd
      - /dev/dri
    ports:
      - "11434:11434"
    restart: unless-stopped
  agent:
    build:
      context: ./agent
      args:
        PYTHON_VERSION: "3.14"
    container_name: localmind_agent
    stdin_open: true
    tty: true
    depends_on:
      - ollama
